openapi: 3.0.0
info:
  title: OdinEye API
  description: OdinEye API Specification
  version: v1
tags:
  - name: boss
    description: Boss related resources
    x-displayName: Bosses

paths:
  /v1/bosses:
    get:
      tags:
        - boss
      summary: List all bosses
      description: Returns a list of in-game bosses with names, keys and defeated status. The number of active bosses is also provided.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BossesResponse'

components:
  schemas:
    BossesResponse:
      description: Represents a bosses response.
      type: object
      properties:
        numberOfActiveBosses:
          type: integer
          description: |-
            Number of currently active bosses.
            An active boss represents a boss that has been summoned but has not yet been defeated.
          format: int32
          minimum: 0
          example: 2
        entries:
          type: array
          items:
            $ref: '#/components/schemas/Boss'
          description: List of bosses.
    Boss:
      description: Represents a boss.
      type: object
      properties:
        key:
          description: Key of the boss.
          type: string
          minLength: 1
          example: gdking
        name:
          description: Name of the boss.
          type: string
          minLength: 1
          example: The Elder
        isDefeated:
          description: If true, the boss has been defeated.
          type: boolean
      