openapi: 3.0.0
info:
  title: OdinEye API
  description: OdinEye API Specification
  version: v1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: server
    description: Server related resources
    x-displayName: Server

paths:
  /serverInfo:
    get:
      tags:
        - server
      summary: Retrieve game server info
      description: Returns general game server information.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerInfo'

components:
  schemas:
    ServerInfo:
      properties:
        maxNumberOfPlayers: 
          type: integer
          description: Maximum number of players permitted on the server.
          format: int32
          minimum: 1
          example: 10
        gameVersion:
          description: Version of the game server.
          type: string
          minLength: 1
          example: 0.217.14
        steamAppId:
          description: Steam application identifier of the game server.
          type: string
          minLength: 1
          example: 892970